version: "3.8"

services:
  app:
    build: .
    container_name: node_task
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
  
  database: 
    image: postgres
    container_name: database_task_node
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@18er0821
      - POSTGRES_DB=API-social-media
    volumes:
      - postgres-data:/var/lib/postgresql/data

  
  redis:
    container_name: redis_db
    image: redis:alpine
    ports: 
      - 6379:6379
volumes:
  postgres-data: