version: "3.8"

services:
  app:
    build: .
    container_name: node
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      - redis

  database:
    container_name: postgres_db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid2
    volumes:
      - pgdata:/data/postgres

  redis:
    container_name: redis_db
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  pgdata:
    driver: local