version: "3"

services:
  app:
    build: .
    container_name: node
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
      - redis

  database:
    image: bitnami/postgresql
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=API-Solid

  redis:
    container_name: redis_db
    image: redis:alpine
    ports:
      - 6379:6379
