version: "3.8"

services:
  postgres:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apiSolid
      PGDATA: /data/postgres

  redis:
    container_name: redis_db
    image: redis:alpine
    ports:
      - 6379:6379
  app:
    build: .
    container_name: node
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
    driver: local